;设置规则标志位

# Custom
surge_ruleset=DIRECT,https://raw.githubusercontent.com/realx1n/x1n/master/conf/Surge/Direct.list
surge_ruleset=世界互联,https://raw.githubusercontent.com/realx1n/x1n/master/conf/Surge/Proxy.list
surge_ruleset=Advertising,https://raw.githubusercontent.com/realx1n/x1n/master/conf/Surge/Reject.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/realx1n/x1n/master/conf/Surge/plex.list
surge_ruleset=狮城,https://raw.githubusercontent.com/realx1n/x1n/refs/heads/master/conf/Surge/AI/cici.list
# Direct+
surge_ruleset=DIRECT,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct+.list

# Reject
surge_ruleset=Advertising,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list
surge_ruleset=Advertising,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Tracking.list
surge_ruleset=Advertising,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Malicious.list

# Streaming
surge_ruleset=世界互联,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/!CN.list
surge_ruleset=YouTube,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/Video/YouTube.list

# App
surge_ruleset=Telegram,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Telegram.list
surge_ruleset=美国,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/PayPal.list
surge_ruleset=Apple,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Apple/Apple.list
#surge_ruleset=Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Steam/Steam.list
surge_ruleset=AI,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list

# Proxy
surge_ruleset=世界互联,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list

# Direct
surge_ruleset=DIRECT,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct.list

# WeChat
surge_ruleset=DIRECT,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/WeChat.list

# Local Area Network
surge_ruleset=LAN,DIRECT

# GeoIP China
surge_ruleset=DIRECT,[]GEOIP,CN

# Proxy+
surge_ruleset=世界互联,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy+.list

# Final
surge_ruleset=世界互联,[]FINAL

;设置规则标志位 


;设置分组标志位

custom_proxy_group=世界互联`select`[]香港`[]狮城`[]美国`[]台湾`[]日本`[]韩国`[]Airplane1`[]Airplane2
custom_proxy_group=香港`select`HK`香港`HongKong
custom_proxy_group=狮城`select`SG`新加坡`狮城`Singapore
custom_proxy_group=美国`select`USA`美国`United States
custom_proxy_group=台湾`select`TW`台湾`Taiwan
custom_proxy_group=日本`select`JP`日本`Japan
custom_proxy_group=韩国`select`KR`韩国`Korea
custom_proxy_group=Telegram`select`[]世界互联`[]香港`[]狮城`[]美国`[]台湾`[]日本`[]韩国`[]Airplane1`[]Airplane2
custom_proxy_group=YouTube`select`[]世界互联`[]香港`[]狮城`[]美国`[]台湾`[]日本`[]韩国`[]Airplane1`[]Airplane2
custom_proxy_group=Apple`select`[]世界互联`[]DIRECT
custom_proxy_group=AI`select`[]世界互联`[]香港`[]狮城`[]美国`[]台湾`[]日本`[]韩国`[]Airplane1`[]Airplane2
#custom_proxy_group=Steam`select`[]DIRECT`[]世界互联
custom_proxy_group=Advertising`select`[]REJECT`[]DIRECT
custom_proxy_group=Airplane1`select`!!GROUPID=0
custom_proxy_group=Airplane2`select`!!GROUPID=2

;设置分组标志位

;自定义 emoji 的选项 
emoji=(Moon),🌕
emoji=(流量|时间|应急),🏳️‍🌈
emoji=(阿联酋|AE|United Arab Emirates),🇦🇪
emoji=(阿根廷|AR|Argentina),🇦🇷
emoji=(澳大利亚|悉尼|AU|Australia|Sydney),🇦🇺
emoji=(巴西|圣保罗|BR|Brazil),🇧🇷
emoji=(加拿大|蒙特利尔|温哥华|CA|Canada),🇨🇦
emoji=(中国|China|GCX),🇨🇳
emoji=(德国|法兰克福|沪德|DE|Germany),🇩🇪
emoji=(法国|巴黎|FR|France),🇫🇷
emoji=(英国|伦敦|UK|England|United Kingdom),🇬🇧
emoji=(香港|深港|沪港|京港|杭港|青港|川港|HK|Hong Kong|HongKong),🇭🇰
emoji=(印度尼西亚|印尼|雅加达|ID|Indonesia),🇮🇩
emoji=(爱尔兰|都柏林|Ireland),🇮🇪
emoji=(日本|东京|大阪|埼玉|沪日|深日|泉日|川日|沪日|JP|Japan),🇯🇵
emoji=(韩国|首尔|沪韩|深韩|KR|Korea),🇰🇷
emoji=(澳门|MO|Macao),🇲🇴
emoji=(马来西亚|MY|Malaysia),🇲🇾
emoji=(荷兰|尼德兰|阿姆斯特丹|NL|Netherlands),🇳🇱
emoji=(菲律宾|PH|Philippines),🇵🇭
emoji=(俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|RU|Russia),🇷🇺
emoji=(瑞典|SE|Sweden),🇸🇪
emoji=(新加坡|狮城|深新|沪新|SG|Singapore),🇸🇬
emoji=(泰国|曼谷|TH|Thailand),🇹🇭
emoji=(土耳其|伊斯坦布尔|TR|Turkey),🇹🇷
emoji=(台湾|台北|台中|新北|彰化|沪台|深台|TW|Taiwan),🇨🇳
emoji=(美国|硅谷|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美|US|USA|America|United States),🇺🇸
emoji=(南非|ZA|South Africa),🇿🇦
emoji=(印度),🇮🇳
emoji=(匈牙利),🇭🇺
emoji=(以色列),🇮🇱
emoji=(哈萨克斯坦),🇰🇿
emoji=(巴基斯坦),🇵🇰
emoji=(柬埔寨),🇰🇭
emoji=(越南),🇻🇳
emoji=(阿塞拜疆),🇦🇿
emoji=(丹麦),🇩🇰
emoji=(乌克兰),🇺🇦
emoji=(冰岛),🇮🇸
emoji=(卢森堡),🇱🇺
emoji=(奥地利|AT),🇦🇹
emoji=(希腊),🇬🇷
emoji=(意大利),🇮🇹
emoji=(挪威),🇳🇴
emoji=(捷克),🇨🇿
emoji=(比利时),🇧🇪
emoji=(波兰),🇵🇱
emoji=(瑞士),🇨🇭
emoji=(芬兰),🇫🇮
emoji=(葡萄牙),🇵🇹
emoji=(西班牙),🇪🇸
emoji=(马恩岛),🇮🇲
emoji=(墨西哥),🇲🇽
emoji=(新西兰),🇳🇿
emoji=(智利),🇨🇱
emoji=(秘鲁),🇵🇪
emoji=(埃及),🇪🇬
emoji=(蒙古),🇲🇳
emoji=(约旦),🇯🇴
emoji=(伊朗),🇮🇷
emoji=(尼泊尔),🇳🇵
emoji=(孟加拉),🇧🇩
emoji=(格鲁吉亚),🇬🇪
emoji=(沙特阿拉伯),🇸🇦
emoji=(吉尔吉斯斯坦),🇰🇬
emoji=(立陶宛),🇱🇹
emoji=(克罗地亚),🇭🇷
emoji=(塞尔维亚),🇷🇸
emoji=(拉脱维亚),🇱🇻
emoji=(摩尔多瓦),🇲🇩
emoji=(斯洛伐克),🇸🇰
emoji=(爱沙尼亚),🇪🇪
emoji=(斯洛文尼亚),🇸🇮
emoji=(阿尔巴尼亚),🇦🇱
emoji=(巴拿马),🇵🇦
emoji=(哥斯达黎加),🇨🇷
emoji=(乌拉圭),🇺🇾
emoji=(哥伦比亚),🇨🇴
emoji=(委内瑞拉),🇻🇪
emoji=(摩洛哥),🇲🇦
emoji=(突尼斯),🇹🇳
emoji=(肯尼亚),🇰🇪
emoji=(尼日利亚),🇳🇬
emoji=(保加利亚),🇧🇬
emoji=(塞浦路斯),🇨🇾
emoji=(北马其顿),🇲🇰
emoji=(罗马尼亚),🇷🇴
emoji=(波黑共和国),🇧🇦
emoji=(越南),🇻🇳
emoji=(迪拜),🇦🇪
emoji=(巴林),🇧🇭
emoji=(亚美尼亚),🇦🇲
emoji=(安道尔),🇦🇩
emoji=(法属留尼汪),🇷🇪
emoji=(波多黎各),🇵🇷
emoji=(巴拉圭),🇵🇾
emoji=(库拉索),🇨🇼
emoji=(厄瓜多尔),🇪🇨
emoji=(斯里兰卡),🇱🇰


;基础配置
overwrite_original_rules=true
surge_rule_base=https://raw.githubusercontent.com/realx1n/x1n/master/conf/sub/Surge_base.conf
clash_rule_base=https://raw.githubusercontent.com/realx1n/x1n/master/conf/sub/Clash_base.yaml
